In [3]:
import polars as pl
import os

In [4]:
data = pl.read_excel('../data/raw/Ejercicio_Tipos_de_Datos.xlsx')
data.head()

shape: (5, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_cliente ┆ nombre_com ┆ genero ┆ fecha_nac ┆ … ┆ talla_cal ┆ canal_con ┆ fecha_ult ┆ monto_ult │
│ ---        ┆ pleto      ┆ ---    ┆ imiento   ┆   ┆ zado      ┆ tacto_pre ┆ ima_compr ┆ ima_compr │
│ i64        ┆ ---        ┆ str    ┆ ---       ┆   ┆ ---       ┆ ferido    ┆ a         ┆ a_ars     │
│            ┆ str        ┆        ┆ str       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆ str       ┆ i64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1001       ┆ Sofía      ┆ M      ┆ 2005-11-1 ┆ … ┆ 42        ┆ Email     ┆ 2023-06-0 ┆ 142990    │
│            ┆ Gómez      ┆        ┆ 9         ┆   ┆           ┆           ┆ 4         ┆           │
│ 1002       ┆ Mateo      ┆ m      ┆ 1960-09-1 ┆ … ┆ 42        ┆ Teléfono  ┆ 2023-11-2 ┆ 156952    │
│            ┆ Fernández  ┆        ┆ 2         ┆   ┆           ┆           ┆ 9         ┆           │
│ 1003       ┆ Valentina  ┆ F      ┆ 12/05/199 ┆ … ┆ 40        ┆ Email     ┆ 2026-07-2 ┆ 138319    │
│            ┆ López      ┆        ┆ 8         ┆   ┆           ┆           ┆ 9         ┆           │
│ 1004       ┆ Lucas      ┆ M      ┆ 1997-08-2 ┆ … ┆ 38        ┆ WhatsApp  ┆ null      ┆ null      │
│            ┆ Martínez   ┆        ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 1005       ┆ Camila     ┆ M      ┆ 1974-10-0 ┆ … ┆ 40        ┆ Email     ┆ 2023-01-2 ┆ 77397     │
│            ┆ Rodríguez  ┆        ┆ 4         ┆   ┆           ┆           ┆ 0         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
data.describe()

shape: (9, 21)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ id_cliente ┆ nombre_co ┆ genero ┆ … ┆ talla_cal ┆ canal_con ┆ fecha_ult ┆ monto_ult │
│ ---        ┆ ---        ┆ mpleto    ┆ ---    ┆   ┆ zado      ┆ tacto_pre ┆ ima_compr ┆ ima_compr │
│ str        ┆ f64        ┆ ---       ┆ str    ┆   ┆ ---       ┆ ferido    ┆ a         ┆ a_ars     │
│            ┆            ┆ str       ┆        ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆ str       ┆ f64       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 52.0       ┆ 51        ┆ 51     ┆ … ┆ 52.0      ┆ 52        ┆ 46        ┆ 45.0      │
│ null_count ┆ 0.0        ┆ 1         ┆ 1      ┆ … ┆ 0.0       ┆ 0         ┆ 6         ┆ 7.0       │
│ mean       ┆ 1025.07692 ┆ null      ┆ null   ┆ … ┆ 39.192308 ┆ null      ┆ null      ┆ 90885.2   │
│            ┆ 3          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ 14.464081  ┆ null      ┆ null   ┆ … ┆ 1.86861   ┆ null      ┆ null      ┆ 50586.372 │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ 775       │
│ min        ┆ 1001.0     ┆ Abril     ┆ F      ┆ … ┆ 36.0      ┆ Email     ┆ 2018-01-1 ┆ -3500.0   │
│            ┆            ┆ Cabrera   ┆        ┆   ┆           ┆           ┆ 5         ┆           │
│ 25%        ┆ 1013.0     ┆ null      ┆ null   ┆ … ┆ 38.0      ┆ null      ┆ null      ┆ 50827.0   │
│ 50%        ┆ 1025.0     ┆ null      ┆ null   ┆ … ┆ 39.0      ┆ null      ┆ null      ┆ 93356.0   │
│ 75%        ┆ 1037.0     ┆ null      ┆ null   ┆ … ┆ 40.0      ┆ null      ┆ null      ┆ 135052.0  │
│ max        ┆ 1050.0     ┆ Zoe       ┆ m      ┆ … ┆ 43.0      ┆ email     ┆ 2027-03-0 ┆ 179275.0  │
│            ┆            ┆ Domínguez ┆        ┆   ┆           ┆           ┆ 1         ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
data.null_count()

shape: (1, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_cliente ┆ nombre_com ┆ genero ┆ fecha_nac ┆ … ┆ talla_cal ┆ canal_con ┆ fecha_ult ┆ monto_ult │
│ ---        ┆ pleto      ┆ ---    ┆ imiento   ┆   ┆ zado      ┆ tacto_pre ┆ ima_compr ┆ ima_compr │
│ u32        ┆ ---        ┆ u32    ┆ ---       ┆   ┆ ---       ┆ ferido    ┆ a         ┆ a_ars     │
│            ┆ u32        ┆        ┆ u32       ┆   ┆ u32       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆           ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 1          ┆ 1      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 6         ┆ 7         │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
data.filter(
    pl.any_horizontal(
        pl.all().is_null()
    )
)

shape: (15, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_cliente ┆ nombre_com ┆ genero ┆ fecha_nac ┆ … ┆ talla_cal ┆ canal_con ┆ fecha_ult ┆ monto_ult │
│ ---        ┆ pleto      ┆ ---    ┆ imiento   ┆   ┆ zado      ┆ tacto_pre ┆ ima_compr ┆ ima_compr │
│ i64        ┆ ---        ┆ str    ┆ ---       ┆   ┆ ---       ┆ ferido    ┆ a         ┆ a_ars     │
│            ┆ str        ┆        ┆ str       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆ str       ┆ i64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1003       ┆ Valentina  ┆ F      ┆ 12/05/199 ┆ … ┆ 40        ┆ Email     ┆ 2026-07-2 ┆ 138319    │
│            ┆ López      ┆        ┆ 8         ┆   ┆           ┆           ┆ 9         ┆           │
│ 1004       ┆ Lucas      ┆ M      ┆ 1997-08-2 ┆ … ┆ 38        ┆ WhatsApp  ┆ null      ┆ null      │
│            ┆ Martínez   ┆        ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 1006       ┆ Beniamín   ┆ F      ┆ 1959-11-1 ┆ … ┆ 39        ┆ Email     ┆ 2026-08-1 ┆ 154362    │
│            ┆ Pérez      ┆        ┆ 1         ┆   ┆           ┆           ┆ 7         ┆           │
│ 1010       ┆ Joaquín    ┆ F      ┆ 1961-03-0 ┆ … ┆ 38        ┆ Teléfono  ┆ 2022-11-1 ┆ 124374    │
│            ┆ Torres     ┆        ┆ 4         ┆   ┆           ┆           ┆ 7         ┆           │
│ 1014       ┆ Bautista   ┆ F      ┆ 1957-06-2 ┆ … ┆ 37        ┆ Redes     ┆ 2027-03-0 ┆ null      │
│            ┆ Silva      ┆        ┆ 3         ┆   ┆           ┆ sociales  ┆ 1         ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1034       ┆ Emiliano   ┆ M      ┆ 1961-04-0 ┆ … ┆ 36        ┆ WhatsApp  ┆ 2026-01-0 ┆ 44507     │
│            ┆ Luna       ┆        ┆ 6         ┆   ┆           ┆           ┆ 3         ┆           │
│ 1035       ┆ Milagros   ┆ F      ┆ 1975-12-1 ┆ … ┆ 36        ┆ Teléfono  ┆ null      ┆ null      │
│            ┆ Correa     ┆        ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 1040       ┆ León       ┆ M      ┆ 1973-01-0 ┆ … ┆ 40        ┆ WhatsApp  ┆ null      ┆ null      │
│            ┆ Guzmán     ┆        ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 1042       ┆ null       ┆ M      ┆ 1963-09-2 ┆ … ┆ 37        ┆ Teléfono  ┆ 2022-03-1 ┆ 176605    │
│            ┆            ┆        ┆ 0         ┆   ┆           ┆           ┆ 0         ┆           │
│ 1045       ┆ Josefina   ┆ M      ┆ 1995-07-2 ┆ … ┆ 40        ┆ Teléfono  ┆ null      ┆ null      │
│            ┆ Toledo     ┆        ┆ 1         ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [22]:
promedio_ingreso_mensual_ars_posgrado = data.filter(
    pl.col('nivel_educativo') == 'Posgrado'
).mean()['ingreso_mensual_ars'].item()

promedio_ingreso_mensual_ars_posgrado

1278915.142857143

In [28]:
data.with_columns(
    pl.col('ingreso_mensual_ars').fill_null(
        pl.col('ingreso_mensual_ars').mean().over('nivel_educativo')
    )
).filter(pl.col('id_cliente') == 1010 )

shape: (1, 20)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_cliente ┆ nombre_com ┆ genero ┆ fecha_nac ┆ … ┆ talla_cal ┆ canal_con ┆ fecha_ult ┆ monto_ult │
│ ---        ┆ pleto      ┆ ---    ┆ imiento   ┆   ┆ zado      ┆ tacto_pre ┆ ima_compr ┆ ima_compr │
│ i64        ┆ ---        ┆ str    ┆ ---       ┆   ┆ ---       ┆ ferido    ┆ a         ┆ a_ars     │
│            ┆ str        ┆        ┆ str       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆ str       ┆ i64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1010       ┆ Joaquín    ┆ F      ┆ 1961-03-0 ┆ … ┆ 38        ┆ Teléfono  ┆ 2022-11-1 ┆ 124374    │
│            ┆ Torres     ┆        ┆ 4         ┆   ┆           ┆           ┆ 7         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘